# Generated by Django 5.1.6 on 2025-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию",
                null=True,
                upload_to="images/blog/",
                verbose_name="Фотография",
            ),
        ),
    ]
