# Generated by Django 5.1.6 on 2025-06-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
