# Generated by Django 5.1.6 on 2025-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/catalog/",
                verbose_name="картинки",
            ),
        ),
    ]
