# Generated by Django 4.2.2 on 2025-06-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_owner_product_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
    ]
